# Exploração inicial da base de dados

##### Esse notebook tem como objetivo realizar a exploração incial da base de dados, identificando sua estrutura e caracterísicas gerais, além de procurar possíveis inconsistências que devem ser tratadas na etapa de limpeza.

---

## Configuração inicial

### Importação das bibliotecas

In [2]:
import pandas as pd
import numpy as np

### Carregamento da base de dados

In [3]:
raw_imdb_df = pd.read_csv("../data/raw/imdb_top_1000.csv")

---
## Compreendendo a base

Nessa etapa, procura-se conhecer a base de dados a partir de informações sobre sua estrutura e alguns exemplos de entradas.

### Estrutura da base

In [4]:
raw_imdb_df.shape

(1000, 16)

In [5]:
raw_imdb_df.columns

Index(['Poster_Link', 'Series_Title', 'Released_Year', 'Certificate',
       'Runtime', 'Genre', 'IMDB_Rating', 'Overview', 'Meta_score', 'Director',
       'Star1', 'Star2', 'Star3', 'Star4', 'No_of_Votes', 'Gross'],
      dtype='object')

In [31]:
raw_imdb_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Poster_Link    1000 non-null   object
 1   Series_Title   1000 non-null   object
 2   Released_Year  1000 non-null   object
 3   Certificate    899 non-null    object
 4   Runtime        1000 non-null   object
 5   Genre          1000 non-null   object
 6   IMDB_Rating    1000 non-null   float64
 7   Overview       1000 non-null   object
 8   Meta_score     843 non-null    float64
 9   Director       1000 non-null   object
 10  Star1          1000 non-null   object
 11  Star2          1000 non-null   object
 12  Star3          1000 non-null   object
 13  Star4          1000 non-null   object
 14  No_of_Votes    1000 non-null   int64
 15  Gross          831 non-null    object
dtypes: float64(2), int64(1), object(13)
memory usage: 125.1+ KB

### Exemplos de entradas

In [7]:
raw_imdb_df.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"

In [9]:
raw_imdb_df.sample(5)

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
697,https://m.media-amazon.com/images/M/MV5BNTEyMz...,Cabaret,1972,A,124 min,"Drama, Music, Musical",7.8,A female girlie club entertainer in Weimar Rep...,80.0,Bob Fosse,Liza Minnelli,Michael York,Helmut Griem,Joel Grey,48334,"42,765,000"
937,https://m.media-amazon.com/images/M/MV5BMTUzND...,The Station Agent,2003,R,89 min,"Comedy, Drama",7.6,"When his only friend dies, a man born with dwa...",81.0,Tom McCarthy,Peter Dinklage,Patricia Clarkson,Bobby Cannavale,Paul Benjamin,67370,"5,739,376"
725,https://m.media-amazon.com/images/M/MV5BNjRlZm...,Mission: Impossible - Fallout,2018,UA,147 min,"Action, Adventure, Thriller",7.7,"Ethan Hunt and his IMF team, along with some f...",86.0,Christopher McQuarrie,Tom Cruise,Henry Cavill,Ving Rhames,Simon Pegg,291257,"220,159,104"
132,https://m.media-amazon.com/images/M/MV5BMjI0OD...,"Three Billboards Outside Ebbing, Missouri",2017,A,115 min,"Comedy, Crime, Drama",8.2,A mother personally challenges the local autho...,88.0,Martin McDonagh,Frances McDormand,Woody Harrelson,Sam Rockwell,Caleb Landry Jones,432610,"54,513,740"
491,https://m.media-amazon.com/images/M/MV5BMTYzND...,Boyhood,2014,A,165 min,Drama,7.9,"The life of Mason, from early childhood to his...",100.0,Richard Linklater,Ellar Coltrane,Patricia Arquette,Ethan Hawke,Elijah Smith,335533,"25,379,975"

### Estatística descritiva

In [34]:
raw_imdb_df.describe()

       IMDB_Rating  Meta_score   No_of_Votes
count  1000.000000  843.000000  1.000000e+03
mean      7.949300   77.971530  2.736929e+05
std       0.275491   12.376099  3.273727e+05
min       7.600000   28.000000  2.508800e+04
25%       7.700000   70.000000  5.552625e+04
50%       7.900000   79.000000  1.385485e+05
75%       8.100000   87.000000  3.741612e+05
max       9.300000  100.000000  2.343110e+06

In [33]:
raw_imdb_df.describe(include="object")

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,Overview,Director,Star1,Star2,Star3,Star4,Gross
count,1000,1000,1000,899,1000,1000,1000,1000,1000,1000,1000,1000,831
unique,1000,999,100,16,140,202,1000,548,660,841,891,939,823
top,https://m.media-amazon.com/images/M/MV5BMTY5OD...,Drishyam,2014,U,100 min,Drama,A man in London tries to help a counter-espion...,Alfred Hitchcock,Tom Hanks,Emma Watson,Rupert Grint,Michael Caine,"4,360,000"
freq,1,2,32,234,23,85,1,14,12,7,5,4,5

### Observações

A partir das informações acima, podemos observar que a base de dados possui 1000 entradas distribuídas entre 16 colunas. Além disso, o tipo de dado da maioria dessas colunas é `object`. O tipo `object` é utilizado pelo Pandas para representar dados textuais quando nenhum tipo mais específico é informado. Algumas dessas colunas realmente representam texto (como `Series_Title`), enquanto outras armazenam números em formato textual (`Released_Year, Runtime e Gross`), exigindo conversão durante a limpeza.

Como pode-se visualizar nos exemplos de entrada, a coluna `Genre`, também, deveria estar formatada como uma lista de `strings`, ao invés de uma só `string` contando vários gêneros. Isso facilitaria uma análise da variável categórica no futuro.

Pensando nisso, a tabela a seguir foi elaborada para facilitar a compreensão da base e das transformações de dados que devem ser feitas na etapa de limpeza.


| Coluna | Descrição | Tipo atual | Tipo esperado |
|--------|-----------|------------|----------------|
| `Poster_Link` | URL do pôster do filme no IMDb. | `object` | `string` |
| `Series_Title` | Título do filme. | `object` | `string` |
| `Released_Year` | Ano de lançamento do filme. | `object` | `int64` |
| `Certificate` | Classificação indicativa do filme. | `object` | `category` |
| `Runtime` | Duração do filme em minutos. | `object` | `int64` |
| `Genre` | Gêneros do filme, separados por vírgulas. | `object` | `object` no formato `list[str]` |
| `IMDB_Rating` | Nota atribuída pelos usuários do IMDb (0–10). | `float64` | `float64` |
| `Overview` | Breve sinopse do filme. | `object` | `string` |
| `Meta_score` | Nota atribuída pelo Metacritic (0–100). | `float64` | `float64`|
| `Director` | Nome do diretor do filme. | `object` | `string` |
| `Star1` | Primeiro ator principal listado. | `object` | `string` |
| `Star2` | Segundo ator principal listado. | `object` | `string` |
| `Star3` | Terceiro ator principal listado. | `object` | `string` |
| `Star4` | Quarto ator principal listado. | `object` | `string` |
| `No_of_votes` | Número de avaliações recebidas no IMDb. | `int64` | `int64` |
| `Gross` | Receita bruta do filme (em dólares). | `object` | `float64` |

Além disso, a base possui como nota máxima 9.3 e como nota mínima 7.6, o que condiz com o fato da base se tratar dos 1000 filmes mais avaliados do IMDb. O gênero mais comum é o de Drama, e a duração mais presente na base é de 100 minutos (1h40). Além disso, o diretor que mais aparece na base de dados é Alfred Hitchcock, e o ator mais frequente como estrela principal é Tom Hanks.

---
## Verificação da qualidade dos dados

Nessa etapa, procuramos por possívels problemas na base de dados que podem ser tratados na etapa de limpeza.

### Valores nulos

In [10]:
null_count = raw_imdb_df.isna().sum()

null_summary = pd.DataFrame({
    "Quantidade de Nulos": null_count,
    "Porcentagem": ( null_count / len(raw_imdb_df)) * 100 
})

null_summary.sort_values(
    by="Porcentagem",
    ascending=False
)

               Quantidade de Nulos  Porcentagem
Gross                          169         16.9
Meta_score                     157         15.7
Certificate                    101         10.1
Poster_Link                      0          0.0
Runtime                          0          0.0
Genre                            0          0.0
Series_Title                     0          0.0
Released_Year                    0          0.0
Overview                         0          0.0
IMDB_Rating                      0          0.0
Star1                            0          0.0
Director                         0          0.0
Star2                            0          0.0
Star3                            0          0.0
Star4                            0          0.0
No_of_Votes                      0          0.0

As colunas `Certificate`, `Meta_score` e `Gross` apresentam entre 10% e 20% de valores nulos entre os preenchimentos. É necessária uma análise mais detalhada dessas entradas com valores nulos, a fim de entender o quanto prejudicam a análise e avaliar a possibilidade de preenchê-las.

### Valores duplicados

In [19]:
duplicate_count = raw_imdb_df.duplicated().sum()

pd.Series(
    {"Registros duplicados": duplicate_count}
)

Registros duplicados    0
dtype: int64

Não existem valores duplicados na base de dados.

### Distribuição das variáveis categóricas

In [12]:
raw_imdb_df["Certificate"].value_counts()

Certificate
U           234
A           197
UA          175
R           146
PG-13        43
PG           37
Passed       34
G            12
Approved     11
TV-PG         3
GP            2
TV-14         1
Unrated       1
TV-MA         1
16            1
U/A           1
Name: count, dtype: int64

In [20]:
raw_imdb_df["Genre"].value_counts()

Genre
Drama                        85
Drama, Romance               37
Comedy, Drama                35
Comedy, Drama, Romance       31
Action, Crime, Drama         30
                             ..
Action, Adventure, Family     1
Action, Crime, Mystery        1
Animation, Drama, Romance     1
Drama, War, Western           1
Adventure, Comedy, War        1
Name: count, Length: 202, dtype: int64

A partir dessa distribuição simples das variáveis categóricas, podemos fazer duas observações:
 1) A coluna `Certificate`, referente à classificação indicativa dos filmes, mistura padrões de classificação de diversos países. Esse detalhe deve ser corrigido na etapa de limpeza, com a adoção de apenas um padrão para todos os filmes.
 2) A coluna `Genre` salva os gêneros dos filmes como uma `string`, com cada gêreno separado por vírgula. Isso pode dificultar análises relacionadas à categoria, sendo necessário transformar o formato da coluna em uma lista de gêneros durante a etapa de limpeza para uma análise mais precisa.

### Verificação de possíveis valores inconsistentes

Nessa etapa, verificamos se, entre as entradas do banco de dados, existe algum valor que não condiz com o esperado para aquela coluna.

#### Variáveis numéricas

In [14]:
raw_imdb_df["IMDB_Rating"].between(0, 10).all()

np.True_

In [15]:
raw_imdb_df["Meta_score"].dropna().between(0, 100).all()

np.True_

Ao avaliar se existem valores fora do escopo das variáveis numéricas, é possível perceber que todas as entradas de `IMDB_Rating` e `Meta_Score` estão de acordo com o esperado.

#### Variáveis `object`

In [16]:
raw_imdb_df["Released_Year"].unique()

array(['1994', '1972', '2008', '1974', '1957', '2003', '1993', '2010',
       '1999', '2001', '1966', '2002', '1990', '1980', '1975', '2020',
       '2019', '2014', '1998', '1997', '1995', '1991', '1977', '1962',
       '1954', '1946', '2011', '2006', '2000', '1988', '1985', '1968',
       '1960', '1942', '1936', '1931', '2018', '2017', '2016', '2012',
       '2009', '2007', '1984', '1981', '1979', '1971', '1963', '1964',
       '1950', '1940', '2013', '2005', '2004', '1992', '1987', '1986',
       '1983', '1976', '1973', '1965', '1959', '1958', '1952', '1948',
       '1944', '1941', '1927', '1921', '2015', '1996', '1989', '1978',
       '1961', '1955', '1953', '1925', '1924', '1982', '1967', '1951',
       '1949', '1939', '1937', '1934', '1928', '1926', '1920', '1970',
       '1969', '1956', '1947', '1945', '1930', '1938', '1935', '1933',
       '1932', '1922', '1943', 'PG'], dtype=object)

In [21]:
raw_imdb_df[
    raw_imdb_df["Released_Year"] == "PG"
]

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
966,https://m.media-amazon.com/images/M/MV5BNjEzYj...,Apollo 13,PG,U,140 min,"Adventure, Drama, History",7.6,NASA must devise a strategy to return Apollo 1...,77.0,Ron Howard,Tom Hanks,Bill Paxton,Kevin Bacon,Gary Sinise,269197,"173,837,933"

Ao analisar a consistência dos valores de `Release_Year`, podemos encontrar uma entrada com o valor "PG" nesse campo, referente ao filme "Apollo 13". Esse erro deve ser tratado na etapa de limpeza.

In [17]:
raw_imdb_df["Runtime"].unique()

array(['142 min', '175 min', '152 min', '202 min', '96 min', '201 min',
       '154 min', '195 min', '148 min', '139 min', '178 min', '161 min',
       '179 min', '136 min', '146 min', '124 min', '133 min', '160 min',
       '132 min', '153 min', '169 min', '130 min', '125 min', '189 min',
       '116 min', '127 min', '118 min', '121 min', '207 min', '122 min',
       '106 min', '112 min', '151 min', '150 min', '155 min', '119 min',
       '110 min', '88 min', '137 min', '89 min', '165 min', '109 min',
       '102 min', '87 min', '126 min', '147 min', '117 min', '181 min',
       '149 min', '105 min', '164 min', '170 min', '98 min', '101 min',
       '113 min', '134 min', '229 min', '115 min', '143 min', '95 min',
       '104 min', '123 min', '131 min', '108 min', '81 min', '99 min',
       '114 min', '129 min', '228 min', '128 min', '103 min', '107 min',
       '68 min', '138 min', '156 min', '167 min', '163 min', '186 min',
       '321 min', '135 min', '140 min', '180 min', '158 min', '210 min',
       '86 min', '162 min', '177 min', '204 min', '91 min', '172 min',
       '45 min', '145 min', '100 min', '196 min', '93 min', '120 min',
       '92 min', '144 min', '80 min', '183 min', '111 min', '141 min',
       '224 min', '171 min', '188 min', '94 min', '185 min', '85 min',
       '205 min', '212 min', '238 min', '72 min', '67 min', '76 min',
       '159 min', '83 min', '90 min', '84 min', '191 min', '197 min',
       '174 min', '97 min', '75 min', '157 min', '209 min', '82 min',
       '220 min', '64 min', '184 min', '168 min', '166 min', '192 min',
       '194 min', '193 min', '69 min', '70 min', '242 min', '79 min',
       '71 min', '78 min'], dtype=object)

Todas as entradas de `Runtime` seguem o mesmo padrão e não existem valores inconsitentes (como tempos de duração muito longos ou entradas que não são tempos de duração).

In [18]:
raw_imdb_df["Gross"].sample(20)

812      4,414,535
19      53,367,844
465      3,313,513
407      3,333,969
463    165,359,751
240        300,000
474     32,381,218
488    115,646,235
569            NaN
82             NaN
680      1,436,000
361     57,366,262
501      3,635,164
529      9,929,135
406     30,857,814
600     70,259,870
810     35,811,509
794      3,029,081
685    238,632,124
81      36,764,313
Name: Gross, dtype: object

As entradas de `Gross` também seguem o mesmo padrão e nao precem ter valores inconsistentes no meio.

---
## Conclusões

A partir da exploração inicial, foi possível observar os seguintes detalhes a respeito da base de dados:
  - Existem 1000 entradas e 16 colunas referentes tanto a informações técnicas do filme, como título, gênero, duração e atores, quanto informações sobre a opinião do público e de críticos, permitindo uma análise detalhada de aspectos que fazem esses filmes serem os mais famosos do IMDb.
  - Algumas colunas precisam passar por uma transformação no tipo de dados para possibilitar uma análise mais detalhada da base, sendo elas: `Genre, Gross, Released_Year e Runtime`. As outras colunas também podem ser formatadas como `string` para utilizar os tipos de dados mais adequados às operações de análise.
  - É necessário avaliar o impacto dos valores nulos na análise da base de dados e avaliar a possibilidade de preenchê-los.
  - É necessário definir um padrão de classificação indicativa para a variável `Certificate`.
  - Existem valores inconsistentes na coluna `Release_Year`